import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// The base URL for our API requests
const BASE_URL = process.env.REACT_APP_BASE_URL_ASP;

// Function to create a base query with our chosen base URL
const createBaseQuery = () => fetchBaseQuery({ baseUrl: BASE_URL });

// List of all the tag types we may use with this API
const TAG_TYPES = ["AuditLogs", "AccountRequests"];

// Function to build our list of endpoints
const createEndpoints = (builder) => {
  return {
    getAuditLogs: builder.query({
      query: () => "management/auditLogs",
      providesTags: ["AuditLogs"],
    }),
    createAccountRequest: builder.mutation({
      query: (requestDetails) => ({
        url: "management/reqAccess",
        method: "POST",
        body: requestDetails,
      }),
    }),
    // Add more endpoints here as needed
  };
};

// Create our API using reduxjs/toolkit/query/react's createApi function
export const adminAuditApi = createApi({
  baseQuery: createBaseQuery(),
  endpoints: createEndpoints,
  reducerPath: "adminAuditApi",
  tagTypes: TAG_TYPES,
});

// Use hooks generated by RTK Query
export const {
  useGetAuditLogsQuery,
  useCreateAccountRequestMutation,
  // Add more exports for other hooks here as needed
} = adminAuditApi;
